modify parse_json_into_columns to handle multiple paths
fullstorydev/dbt_fullstory pull request #9
Opened 2023-11-03 14:08 UTC by huttotw

This adds a new field `additional_paths` where we will look in order for values if the `path` does not return a valid json value. This functions basically like COALESCE.

2023-11-03 20:11 UTC, sgagofs approved these changes
LGTM! This looks like a good change.

2023-11-06 16:41 UTC, craigrmccown reviewed
To simplify this a bit, should we use a single `paths` configuration? Or, do you think that supporting both `path` and `additional_paths` is more ergonomic because a single path is most common?

2023-11-06 19:36 UTC, huttotw commented
I like that suggestion @craigrmccown, updated!

2023-11-06 21:07 UTC, camphillips22 commented on models/staging/stg_events__all.sql
> +                        "$.watched_element.target.named_element_id",
Why do we need these paths? `element_definition_id` should only show up in a single field, `$.element_definition_id`.

2023-11-06 21:11 UTC, craigrmccown commented on models/staging/stg_events__all.sql
> +                        "$.watched_element.target.named_element_id",
Are these paths correct? Are there examples of event data that contains these paths? I'm looking at the types we use to serialize this data, and I don't see these paths. Also, the event type prefix is unfamiliar to me.

2023-11-06 21:50 UTC, camphillips22 requested changes
Blocking this for now. While I'm not necessarily opposed to the functionality, we should never have to do this coalescing as our data model should only contain the data in a single place.

2023-11-06 21:59 UTC, huttotw commented
> we should never have to do this coalescing as our data model should only contain the data in a single place.

Agreed. I confirmed that I was developing against a old copy of data and the issue that this PR would have solved is not actually present. Closing.

2023-11-06 21:59 UTC, closed without merging